use crate::models::{AppearanceConfig, PaletteColors};
use crate::paths::write_to_config_and_live;

fn hex_clean(h: &str) -> &str {
    h.trim_start_matches('#')
}

pub struct AppearancePopulator;

impl AppearancePopulator {
    pub fn populate_appearance(config: &AppearanceConfig) -> anyhow::Result<()> {
        let f = &config.fonts;
        let a = &config.appearance;

        // 1. kitty/appearance.conf
        let mut kitty = format!(
            "# Auto-generated by appearance-populator - Do not edit manually\n\
             font_family      {}\n\
             font_size        {:.1}\n",
            f.mono.family, f.sizes.terminal
        );
        if !f.mono.italic_family.is_empty() && f.mono.italic_family != f.mono.family {
            kitty.push_str(&format!("italic_font      {}\n", f.mono.italic_family));
        }
        if !f.mono.features.is_empty() {
            kitty.push_str(&format!("font_features    {}\n", f.mono.features));
        }
        write_to_config_and_live("kitty/appearance.conf", &kitty)?;

        // 2. fuzzel/appearance.ini
        let fuzzel = format!(
            "# Auto-generated by appearance-populator - Do not edit manually\n\
             [main]\n\
             font={}:size={}\n\
             terminal=kitty\n\n\
             [border]\n\
             width={}\n\
             radius={}\n",
            f.mono.family,
            f.sizes.launcher.floor() as u32,
            a.border_width,
            a.border_radius
        );
        write_to_config_and_live("fuzzel/appearance.ini", &fuzzel)?;

        // 3. colors/appearance.css
        let colors_css = format!(
            "/* Auto-generated by appearance-populator - Do not edit manually */\n\n\
             @define-color font_mono \"{}\";\n\
             @define-color font_sans \"{}\";\n\
             @define-color font_serif \"{}\";\n\n\
             :root, * {{\n\
               --font-mono: \"{}\";\n\
               --font-sans: \"{}\";\n\
               --font-serif: \"{}\";\n\
               --font-size-terminal: {:.1}pt;\n\
               --font-size-bar: {:.1}pt;\n\
               --font-size-launcher: {:.1}pt;\n\
               --font-size-desktop: {:.1}pt;\n\
               --font-size-power-menu: {:.1}pt;\n\
               --border-radius: {}px;\n\
               --border-width: {}px;\n\
               --gap-inner: {}px;\n\
               --gap-outer: {}px;\n\
             }}\n",
            f.mono.family,
            f.sans.family,
            f.serif.family,
            f.mono.family,
            f.sans.family,
            f.serif.family,
            f.sizes.terminal,
            f.sizes.bar,
            f.sizes.launcher,
            f.sizes.desktop,
            f.sizes.power_menu,
            a.border_radius,
            a.border_width,
            a.gaps.inner,
            a.gaps.outer
        );
        write_to_config_and_live("colors/appearance.css", &colors_css)?;

        // 4. wlogout/appearance.css
        let wlogout = format!(
            "/* Auto-generated by appearance-populator - Do not edit manually */\n\
             @define-color font_family \"{}\";\n\
             @define-color font_size {:.1}pt;\n\
             @define-color border_radius {}px;\n\
             @define-color border_width {}px;\n\n\
             :root, * {{\n\
               --font-family: \"{}\";\n\
               --font-size: {:.1}pt;\n\
               --border-radius: {}px;\n\
               --border-width: {}px;\n\
             }}\n",
            f.sans.family,
            f.sizes.power_menu,
            a.border_radius,
            a.border_width,
            f.sans.family,
            f.sizes.power_menu,
            a.border_radius,
            a.border_width
        );
        write_to_config_and_live("wlogout/appearance.css", &wlogout)?;

        // 5. wayle/appearance.toml
        let rounding_str = if a.border_radius == 0 {
            "none".to_string()
        } else {
            format!("{}px", a.border_radius)
        };
        let wayle = format!(
            "# Auto-generated by appearance-populator - Do not edit manually\n\
             [general]\n\
             font-sans = \"{}\"\n\n\
             [styling]\n\
             rounding = \"{}\"\n",
            f.mono.family, rounding_str
        );
        write_to_config_and_live("wayle/appearance.toml", &wayle)?;

        Ok(())
    }

    pub fn populate_theme_tokens(colors: &PaletteColors, appearance: &AppearanceConfig) -> anyhow::Result<()> {
        let c = colors;
        let a = &appearance.appearance;

        // 1. colors/colors.sh
        let colors_sh = format!(
            "#!/usr/bin/env bash\n\
             # =============================================================================\n\
             #  Theme Generated Shell Environment Variables\n\
             # =============================================================================\n\n\
             export THEME_BG=\"{}\"\n\
             export THEME_BG_DARK=\"{}\"\n\
             export THEME_BG_CARD=\"{}\"\n\
             export THEME_FG=\"{}\"\n\
             export THEME_FG_MUTED=\"{}\"\n\
             export THEME_ACCENT=\"{}\"\n\n\
             export THEME_BLUE=\"{}\"\n\
             export THEME_CYAN=\"{}\"\n\
             export THEME_GREEN=\"{}\"\n\
             export THEME_YELLOW=\"{}\"\n\
             export THEME_ORANGE=\"{}\"\n\
             export THEME_RED=\"{}\"\n\
             export THEME_MAGENTA=\"{}\"\n\
             export THEME_COMMENT=\"{}\"\n\n\
             export THEME_COLOR0=\"{}\"\n\
             export THEME_COLOR1=\"{}\"\n\
             export THEME_COLOR2=\"{}\"\n\
             export THEME_COLOR3=\"{}\"\n\
             export THEME_COLOR4=\"{}\"\n\
             export THEME_COLOR5=\"{}\"\n\
             export THEME_COLOR6=\"{}\"\n\
             export THEME_COLOR7=\"{}\"\n\
             export THEME_COLOR8=\"{}\"\n\
             export THEME_COLOR9=\"{}\"\n\
             export THEME_COLOR10=\"{}\"\n\
             export THEME_COLOR11=\"{}\"\n\
             export THEME_COLOR12=\"{}\"\n\
             export THEME_COLOR13=\"{}\"\n\
             export THEME_COLOR14=\"{}\"\n\
             export THEME_COLOR15=\"{}\"\n",
            c.background, c.color0, c.color8, c.foreground, c.color7, c.accent,
            c.color4, c.color6, c.color2, c.color3, c.color11, c.color1, c.color5, c.color8,
            c.color0, c.color1, c.color2, c.color3, c.color4, c.color5, c.color6, c.color7,
            c.color8, c.color9, c.color10, c.color11, c.color12, c.color13, c.color14, c.color15
        );
        write_to_config_and_live("colors/colors.sh", &colors_sh)?;

        // 2. colors/vars.css & wlogout/vars.css
        let vars_css = format!(
            "/* =============================================================================\n\
             *  Theme Generated CSS Variables\n\
             * ============================================================================= */\n\n\
             @define-color bg {};\n\
             @define-color bg_dark {};\n\
             @define-color bg_card {};\n\
             @define-color bg_highlight {};\n\n\
             @define-color fg {};\n\
             @define-color fg_muted {};\n\
             @define-color comment {};\n\n\
             @define-color blue {};\n\
             @define-color cyan {};\n\
             @define-color teal {};\n\
             @define-color green {};\n\
             @define-color yellow {};\n\
             @define-color orange {};\n\
             @define-color red {};\n\
             @define-color magenta {};\n\n\
             @define-color border_color {};\n\
             @define-color border_focus {};\n\
             @define-color accent {};\n\n\
             /* Base16 standard color indices */\n\
             @define-color color0 {};\n\
             @define-color color1 {};\n\
             @define-color color2 {};\n\
             @define-color color3 {};\n\
             @define-color color4 {};\n\
             @define-color color5 {};\n\
             @define-color color6 {};\n\
             @define-color color7 {};\n\
             @define-color color8 {};\n\
             @define-color color9 {};\n\
             @define-color color10 {};\n\
             @define-color color11 {};\n\
             @define-color color12 {};\n\
             @define-color color13 {};\n\
             @define-color color14 {};\n\
             @define-color color15 {};\n",
            c.background, c.color0, c.color8, c.color8,
            c.foreground, c.color7, c.color8,
            c.color4, c.color6, c.color6, c.color2, c.color3, c.color11, c.color1, c.color5,
            c.color8, c.color4, c.accent,
            c.color0, c.color1, c.color2, c.color3, c.color4, c.color5, c.color6, c.color7,
            c.color8, c.color9, c.color10, c.color11, c.color12, c.color13, c.color14, c.color15
        );
        write_to_config_and_live("colors/vars.css", &vars_css)?;
        write_to_config_and_live("wlogout/vars.css", &vars_css)?;

        // 3. kitty/colors.conf
        let kitty_colors = format!(
            "# =============================================================================\n\
             #  Theme Generated Kitty Colors\n\
             # =============================================================================\n\n\
             background {}\n\
             foreground {}\n\
             selection_background {}\n\
             selection_foreground {}\n\
             url_color {}\n\
             cursor {}\n\
             cursor_text_color {}\n\n\
             active_tab_background {}\n\
             active_tab_foreground {}\n\
             inactive_tab_background {}\n\
             inactive_tab_foreground {}\n\
             tab_bar_background {}\n\n\
             active_border_color {}\n\
             inactive_border_color {}\n\
             bell_border_color {}\n\n\
             color0 {}\n\
             color1 {}\n\
             color2 {}\n\
             color3 {}\n\
             color4 {}\n\
             color5 {}\n\
             color6 {}\n\
             color7 {}\n\
             color8 {}\n\
             color9 {}\n\
             color10 {}\n\
             color11 {}\n\
             color12 {}\n\
             color13 {}\n\
             color14 {}\n\
             color15 {}\n",
            c.background, c.foreground, c.color8, c.foreground, c.color6, c.cursor, c.background,
            c.color4, c.background, c.color0, c.color7, c.background,
            c.color4, c.color0, c.color1,
            c.color0, c.color1, c.color2, c.color3, c.color4, c.color5, c.color6, c.color7,
            c.color8, c.color9, c.color10, c.color11, c.color12, c.color13, c.color14, c.color15
        );
        write_to_config_and_live("kitty/colors.conf", &kitty_colors)?;

        // 4. fuzzel/colors.ini
        let fuzzel_colors = format!(
            "# =============================================================================\n\
             #  Theme Generated Fuzzel Palette\n\
             # =============================================================================\n\n\
             [colors]\n\
             background={}f2\n\
             text={}ff\n\
             prompt={}ff\n\
             placeholder={}ff\n\
             input={}ff\n\
             match={}ff\n\
             selection={}ff\n\
             selection-text={}ff\n\
             selection-match={}ff\n\
             border={}ff\n",
            hex_clean(&c.background),
            hex_clean(&c.foreground),
            hex_clean(&c.color4),
            hex_clean(&c.color8),
            hex_clean(&c.foreground),
            hex_clean(&c.color5),
            hex_clean(&c.color8),
            hex_clean(&c.foreground),
            hex_clean(&c.color6),
            hex_clean(&c.color4)
        );
        write_to_config_and_live("fuzzel/colors.ini", &fuzzel_colors)?;

        // 5. wayle/colors.toml
        let wayle_colors = format!(
            "# =============================================================================\n\
             #  Theme Generated Wayle Palette\n\
             # =============================================================================\n\n\
             [styling.palette]\n\
             bg = \"{}\"\n\
             surface = \"{}\"\n\
             elevated = \"{}\"\n\
             fg = \"{}\"\n\
             fg-muted = \"{}\"\n\
             primary = \"{}\"\n\
             red = \"{}\"\n\
             yellow = \"{}\"\n\
             green = \"{}\"\n\
             blue = \"{}\"\n",
            c.background, c.background, c.color0, c.foreground, c.color7,
            c.color13, c.color1, c.color3, c.color2, c.color12
        );
        write_to_config_and_live("wayle/colors.toml", &wayle_colors)?;

        // 6. niri/colors.kdl
        let niri_colors = format!(
            "// =============================================================================\n\
             //  Theme Generated Niri Layout & Border Colors\n\
             // =============================================================================\n\n\
             layout {{\n\
                 gaps {}\n\
                 background-color \"{}\"\n\n\
                 border {{\n\
                     width {}\n\
                     active-color \"{}\"\n\
                     inactive-color \"{}\"\n\
                     urgent-color \"{}\"\n\
                 }}\n\n\
                 focus-ring {{\n\
                     width {}\n\
                     active-color \"{}\"\n\
                     inactive-color \"{}\"\n\
                     urgent-color \"{}\"\n\
                 }}\n\n\
                 shadow {{\n\
                     color \"#00000080\"\n\
                 }}\n\n\
                 tab-indicator {{\n\
                     active-color \"{}\"\n\
                     inactive-color \"{}\"\n\
                     urgent-color \"{}\"\n\
                 }}\n\n\
                 insert-hint {{\n\
                     color \"{}80\"\n\
                 }}\n\
             }}\n\n\
             overview {{\n\
                 backdrop-color \"{}e0\"\n\
             }}\n",
            a.gaps.inner,
            c.color0,
            a.border_width,
            c.color4, c.color8, c.color1,
            a.border_width,
            c.color4, c.color8, c.color1,
            c.color4, c.color8, c.color1,
            c.color4,
            c.color0
        );
        write_to_config_and_live("niri/colors.kdl", &niri_colors)?;

        // 7. labwc/themerc-override
        let themerc = format!(
            "# =============================================================================\n\
             #  Theme Generated Labwc Override\n\
             # =============================================================================\n\n\
             border.width: {}\n\
             window.active.border.color: {}\n\
             window.inactive.border.color: #050508\n\n\
             window.titlebar.padding.width: 10\n\
             window.titlebar.padding.height: 3\n\
             window.active.title.bg: Solid\n\
             window.active.title.bg.color: {}\n\
             window.inactive.title.bg: Solid\n\
             window.inactive.title.bg.color: #050508\n\n\
             window.active.label.text.color: {}\n\
             window.inactive.label.text.color: #3B3E52\n\
             window.label.text.justify: Center\n\n\
             window.button.width: 14\n\
             window.button.height: 14\n\
             window.button.spacing: 8\n\
             window.button.hover.bg.color: #313244\n\
             window.button.hover.bg.corner-radius: 7\n\n\
             window.active.button.close.unpressed.image.color: #FF5F56\n\
             window.active.button.iconify.unpressed.image.color: #FFBD2E\n\
             window.active.button.max.unpressed.image.color: #27C93F\n\n\
             window.inactive.button.close.unpressed.image.color: #14141E\n\
             window.inactive.button.iconify.unpressed.image.color: #14141E\n\
             window.inactive.button.max.unpressed.image.color: #14141E\n\n\
             window.active.shadow.size: 20\n\
             window.inactive.shadow.size: 0\n\
             window.active.shadow.color: #000000C0\n\
             window.inactive.shadow.color: #00000000\n\n\
             snapping.overlay.edge.bg.color: {}33\n\
             snapping.overlay.edge.border.color: {}\n\
             snapping.overlay.edge.border.width: {}\n\
             snapping.overlay.region.bg.color: {}33\n\
             snapping.overlay.region.border.color: {}\n\
             snapping.overlay.region.border.width: {}\n\n\
             osd.bg.color: {}E0\n\
             osd.border.color: {}\n\
             osd.border.width: {}\n\
             osd.label.text.color: {}\n\n\
             menu.border.width: {}\n\
             menu.border.color: {}\n\
             menu.items.bg.color: {}\n\
             menu.items.text.color: {}\n\
             menu.items.active.bg.color: {}\n\
             menu.items.active.text.color: {}\n",
            a.border_width,
            c.color4,
            c.color0,
            c.foreground,
            c.color4, c.color4, a.border_width,
            c.color4, c.color4, a.border_width,
            c.color0, c.color4, a.border_width, c.foreground,
            a.border_width, c.color4,
            c.color0, c.foreground, c.color4, c.color0
        );
        write_to_config_and_live("labwc/themerc-override", &themerc)?;

        // 8. swaylock/config
        let swaylock = format!(
            "# =============================================================================\n\
             #  Theme Generated Swaylock-Effects Config\n\
             # =============================================================================\n\n\
             screenshots\n\
             clock\n\
             indicator\n\
             indicator-radius=120\n\
             indicator-thickness=10\n\
             indicator-idle-visible\n\
             effect-blur=7x5\n\
             effect-vignette=0.5:0.5\n\
             fade-in=0.2\n\
             grace=2\n\
             grace-no-mouse\n\
             grace-no-touch\n\
             font=\"{}\"\n\n\
             color={}\n\n\
             ring-color={}\n\
             ring-clear-color={}\n\
             ring-caps-lock-color={}\n\
             ring-ver-color={}\n\
             ring-wrong-color={}\n\n\
             inside-color={}b3\n\
             inside-clear-color={}b3\n\
             inside-caps-lock-color={}b3\n\
             inside-ver-color={}b3\n\
             inside-wrong-color={}b3\n\n\
             key-hl-color={}\n\
             bs-hl-color={}\n\n\
             line-color={}00\n\
             line-clear-color={}00\n\
             line-caps-lock-color={}00\n\
             line-ver-color={}00\n\
             line-wrong-color={}00\n\
             separator-color={}00\n\n\
             text-color={}\n\
             text-clear-color={}\n\
             text-caps-lock-color={}\n\
             text-ver-color={}\n\
             text-wrong-color={}\n",
            appearance.fonts.sans.family,
            hex_clean(&c.background),
            hex_clean(&c.color4),
            hex_clean(&c.color2),
            hex_clean(&c.color3),
            hex_clean(&c.color4),
            hex_clean(&c.color1),
            hex_clean(&c.background),
            hex_clean(&c.background),
            hex_clean(&c.background),
            hex_clean(&c.background),
            hex_clean(&c.background),
            hex_clean(&c.color5),
            hex_clean(&c.color1),
            hex_clean(&c.background),
            hex_clean(&c.background),
            hex_clean(&c.background),
            hex_clean(&c.background),
            hex_clean(&c.background),
            hex_clean(&c.background),
            hex_clean(&c.foreground),
            hex_clean(&c.foreground),
            hex_clean(&c.color3),
            hex_clean(&c.foreground),
            hex_clean(&c.color1)
        );
        write_to_config_and_live("swaylock/config", &swaylock)?;

        // 9. wallust stylix.jsonc colorscheme format
        let wallust_json = serde_json::json!({
            "special": {
                "background": c.background,
                "foreground": c.foreground,
                "cursor": c.cursor
            },
            "colors": {
                "color0": c.color0,
                "color1": c.color1,
                "color2": c.color2,
                "color3": c.color3,
                "color4": c.color4,
                "color5": c.color5,
                "color6": c.color6,
                "color7": c.color7,
                "color8": c.color8,
                "color9": c.color9,
                "color10": c.color10,
                "color11": c.color11,
                "color12": c.color12,
                "color13": c.color13,
                "color14": c.color14,
                "color15": c.color15
            }
        });
        let wallust_str = serde_json::to_string_pretty(&wallust_json)?;
        write_to_config_and_live("wallust/colorschemes/stylix.jsonc", &wallust_str)?;

        Ok(())
    }
}
