use crate::models::{PaletteColors, ThemeDefinition};

pub fn get_builtin_themes() -> Vec<ThemeDefinition> {
    vec![
        ThemeDefinition {
            name: "catppuccin-mocha".to_string(),
            display_name: Some("Catppuccin Mocha".to_string()),
            polarity: "dark".to_string(),
            colors: PaletteColors {
                background: "#1e1e2e".to_string(),
                foreground: "#cdd6f4".to_string(),
                cursor: "#f5e0dc".to_string(),
                accent: "#89b4fa".to_string(),
                color0: "#1e1e2e".to_string(),
                color1: "#f38ba8".to_string(),
                color2: "#a6e3a1".to_string(),
                color3: "#f9e2af".to_string(),
                color4: "#89b4fa".to_string(),
                color5: "#cba6f7".to_string(),
                color6: "#94e2d5".to_string(),
                color7: "#cdd6f4".to_string(),
                color8: "#6c7086".to_string(),
                color9: "#f38ba8".to_string(),
                color10: "#a6e3a1".to_string(),
                color11: "#fab387".to_string(),
                color12: "#89b4fa".to_string(),
                color13: "#cba6f7".to_string(),
                color14: "#94e2d5".to_string(),
                color15: "#b4befe".to_string(),
            },
        },
        ThemeDefinition {
            name: "catppuccin-latte".to_string(),
            display_name: Some("Catppuccin Latte".to_string()),
            polarity: "light".to_string(),
            colors: PaletteColors {
                background: "#eff1f5".to_string(),
                foreground: "#4c4f69".to_string(),
                cursor: "#dc8a78".to_string(),
                accent: "#1e66f5".to_string(),
                color0: "#eff1f5".to_string(),
                color1: "#d20f39".to_string(),
                color2: "#40a02b".to_string(),
                color3: "#df8e1d".to_string(),
                color4: "#1e66f5".to_string(),
                color5: "#8839ef".to_string(),
                color6: "#179299".to_string(),
                color7: "#4c4f69".to_string(),
                color8: "#9ca0b0".to_string(),
                color9: "#d20f39".to_string(),
                color10: "#40a02b".to_string(),
                color11: "#fe640b".to_string(),
                color12: "#1e66f5".to_string(),
                color13: "#8839ef".to_string(),
                color14: "#179299".to_string(),
                color15: "#7287fd".to_string(),
            },
        },
        ThemeDefinition {
            name: "catppuccin-macchiato".to_string(),
            display_name: Some("Catppuccin Macchiato".to_string()),
            polarity: "dark".to_string(),
            colors: PaletteColors {
                background: "#24273a".to_string(),
                foreground: "#cad3f5".to_string(),
                cursor: "#f4dbd6".to_string(),
                accent: "#8aadf4".to_string(),
                color0: "#1e2030".to_string(),
                color1: "#ed8796".to_string(),
                color2: "#a6da95".to_string(),
                color3: "#eed49f".to_string(),
                color4: "#8aadf4".to_string(),
                color5: "#c6a0f6".to_string(),
                color6: "#8bd5ca".to_string(),
                color7: "#cad3f5".to_string(),
                color8: "#5b6078".to_string(),
                color9: "#ed8796".to_string(),
                color10: "#a6da95".to_string(),
                color11: "#f5a97f".to_string(),
                color12: "#8aadf4".to_string(),
                color13: "#c6a0f6".to_string(),
                color14: "#8bd5ca".to_string(),
                color15: "#b7bdf8".to_string(),
            },
        },
        ThemeDefinition {
            name: "catppuccin-frappe".to_string(),
            display_name: Some("Catppuccin Frappé".to_string()),
            polarity: "dark".to_string(),
            colors: PaletteColors {
                background: "#303446".to_string(),
                foreground: "#c6d0f5".to_string(),
                cursor: "#f2d5cf".to_string(),
                accent: "#8caaee".to_string(),
                color0: "#292c3c".to_string(),
                color1: "#e78284".to_string(),
                color2: "#a6d189".to_string(),
                color3: "#e5c890".to_string(),
                color4: "#8caaee".to_string(),
                color5: "#ca9ee6".to_string(),
                color6: "#81c8be".to_string(),
                color7: "#c6d0f5".to_string(),
                color8: "#626880".to_string(),
                color9: "#e78284".to_string(),
                color10: "#a6d189".to_string(),
                color11: "#ef9f76".to_string(),
                color12: "#8caaee".to_string(),
                color13: "#ca9ee6".to_string(),
                color14: "#81c8be".to_string(),
                color15: "#b5bfe2".to_string(),
            },
        },
        ThemeDefinition {
            name: "tokyo-night".to_string(),
            display_name: Some("Tokyo Night".to_string()),
            polarity: "dark".to_string(),
            colors: PaletteColors {
                background: "#1a1b26".to_string(),
                foreground: "#c0caf5".to_string(),
                cursor: "#c0caf5".to_string(),
                accent: "#7aa2f7".to_string(),
                color0: "#15161e".to_string(),
                color1: "#f7768e".to_string(),
                color2: "#9ece6a".to_string(),
                color3: "#e0af68".to_string(),
                color4: "#7aa2f7".to_string(),
                color5: "#bb9af7".to_string(),
                color6: "#7dcfff".to_string(),
                color7: "#a9b1d6".to_string(),
                color8: "#414868".to_string(),
                color9: "#f7768e".to_string(),
                color10: "#9ece6a".to_string(),
                color11: "#ff9e64".to_string(),
                color12: "#7aa2f7".to_string(),
                color13: "#bb9af7".to_string(),
                color14: "#7dcfff".to_string(),
                color15: "#c0caf5".to_string(),
            },
        },
        ThemeDefinition {
            name: "tokyo-night-storm".to_string(),
            display_name: Some("Tokyo Night Storm".to_string()),
            polarity: "dark".to_string(),
            colors: PaletteColors {
                background: "#24283b".to_string(),
                foreground: "#c0caf5".to_string(),
                cursor: "#c0caf5".to_string(),
                accent: "#7aa2f7".to_string(),
                color0: "#1d202f".to_string(),
                color1: "#f7768e".to_string(),
                color2: "#9ece6a".to_string(),
                color3: "#e0af68".to_string(),
                color4: "#7aa2f7".to_string(),
                color5: "#bb9af7".to_string(),
                color6: "#7dcfff".to_string(),
                color7: "#a9b1d6".to_string(),
                color8: "#414868".to_string(),
                color9: "#f7768e".to_string(),
                color10: "#9ece6a".to_string(),
                color11: "#ff9e64".to_string(),
                color12: "#7aa2f7".to_string(),
                color13: "#bb9af7".to_string(),
                color14: "#7dcfff".to_string(),
                color15: "#c0caf5".to_string(),
            },
        },
        ThemeDefinition {
            name: "tokyo-night-moon".to_string(),
            display_name: Some("Tokyo Night Moon".to_string()),
            polarity: "dark".to_string(),
            colors: PaletteColors {
                background: "#222436".to_string(),
                foreground: "#c8d3f5".to_string(),
                cursor: "#c8d3f5".to_string(),
                accent: "#82aaff".to_string(),
                color0: "#1b1d2b".to_string(),
                color1: "#ff757f".to_string(),
                color2: "#c3e88d".to_string(),
                color3: "#ffc777".to_string(),
                color4: "#82aaff".to_string(),
                color5: "#c099ff".to_string(),
                color6: "#86e1fc".to_string(),
                color7: "#828bb8".to_string(),
                color8: "#3b4261".to_string(),
                color9: "#ff757f".to_string(),
                color10: "#c3e88d".to_string(),
                color11: "#ff966c".to_string(),
                color12: "#82aaff".to_string(),
                color13: "#c099ff".to_string(),
                color14: "#86e1fc".to_string(),
                color15: "#c8d3f5".to_string(),
            },
        },
        ThemeDefinition {
            name: "tokyo-night-day".to_string(),
            display_name: Some("Tokyo Night Day".to_string()),
            polarity: "light".to_string(),
            colors: PaletteColors {
                background: "#e1e2e7".to_string(),
                foreground: "#3760bf".to_string(),
                cursor: "#3760bf".to_string(),
                accent: "#2e7de9".to_string(),
                color0: "#e1e2e7".to_string(),
                color1: "#f52a65".to_string(),
                color2: "#587539".to_string(),
                color3: "#8c6c3e".to_string(),
                color4: "#2e7de9".to_string(),
                color5: "#9854f1".to_string(),
                color6: "#007197".to_string(),
                color7: "#6172b0".to_string(),
                color8: "#a8aecb".to_string(),
                color9: "#f52a65".to_string(),
                color10: "#587539".to_string(),
                color11: "#b15c00".to_string(),
                color12: "#2e7de9".to_string(),
                color13: "#9854f1".to_string(),
                color14: "#007197".to_string(),
                color15: "#3760bf".to_string(),
            },
        },
        ThemeDefinition {
            name: "gruvbox-dark".to_string(),
            display_name: Some("Gruvbox Dark".to_string()),
            polarity: "dark".to_string(),
            colors: PaletteColors {
                background: "#282828".to_string(),
                foreground: "#ebdbb2".to_string(),
                cursor: "#ebdbb2".to_string(),
                accent: "#83a598".to_string(),
                color0: "#282828".to_string(),
                color1: "#cc241d".to_string(),
                color2: "#98971a".to_string(),
                color3: "#d79921".to_string(),
                color4: "#458588".to_string(),
                color5: "#b16286".to_string(),
                color6: "#689d6a".to_string(),
                color7: "#a89984".to_string(),
                color8: "#928374".to_string(),
                color9: "#fb4934".to_string(),
                color10: "#b8bb26".to_string(),
                color11: "#fe8019".to_string(),
                color12: "#83a598".to_string(),
                color13: "#d3869b".to_string(),
                color14: "#8ec07c".to_string(),
                color15: "#ebdbb2".to_string(),
            },
        },
        ThemeDefinition {
            name: "gruvbox-light".to_string(),
            display_name: Some("Gruvbox Light".to_string()),
            polarity: "light".to_string(),
            colors: PaletteColors {
                background: "#fbf1c7".to_string(),
                foreground: "#3c3836".to_string(),
                cursor: "#3c3836".to_string(),
                accent: "#458588".to_string(),
                color0: "#fbf1c7".to_string(),
                color1: "#cc241d".to_string(),
                color2: "#98971a".to_string(),
                color3: "#d79921".to_string(),
                color4: "#458588".to_string(),
                color5: "#b16286".to_string(),
                color6: "#689d6a".to_string(),
                color7: "#7c6f64".to_string(),
                color8: "#928374".to_string(),
                color9: "#9d0006".to_string(),
                color10: "#79740e".to_string(),
                color11: "#af3a03".to_string(),
                color12: "#076678".to_string(),
                color13: "#8f3f71".to_string(),
                color14: "#427b58".to_string(),
                color15: "#3c3836".to_string(),
            },
        },
        ThemeDefinition {
            name: "nord".to_string(),
            display_name: Some("Nord".to_string()),
            polarity: "dark".to_string(),
            colors: PaletteColors {
                background: "#2e3440".to_string(),
                foreground: "#d8dee9".to_string(),
                cursor: "#d8dee9".to_string(),
                accent: "#88c0d0".to_string(),
                color0: "#3b4252".to_string(),
                color1: "#bf616a".to_string(),
                color2: "#a3be8c".to_string(),
                color3: "#ebcb8b".to_string(),
                color4: "#81a1c1".to_string(),
                color5: "#b48ead".to_string(),
                color6: "#88c0d0".to_string(),
                color7: "#e5e9f0".to_string(),
                color8: "#4c566a".to_string(),
                color9: "#bf616a".to_string(),
                color10: "#a3be8c".to_string(),
                color11: "#d08770".to_string(),
                color12: "#81a1c1".to_string(),
                color13: "#b48ead".to_string(),
                color14: "#8fbcbb".to_string(),
                color15: "#eceff4".to_string(),
            },
        },
        ThemeDefinition {
            name: "dracula".to_string(),
            display_name: Some("Dracula".to_string()),
            polarity: "dark".to_string(),
            colors: PaletteColors {
                background: "#282a36".to_string(),
                foreground: "#f8f8f2".to_string(),
                cursor: "#f8f8f2".to_string(),
                accent: "#bd93f9".to_string(),
                color0: "#21222c".to_string(),
                color1: "#ff5555".to_string(),
                color2: "#50fa7b".to_string(),
                color3: "#f1fa8c".to_string(),
                color4: "#bd93f9".to_string(),
                color5: "#ff79c6".to_string(),
                color6: "#8be9fd".to_string(),
                color7: "#f8f8f2".to_string(),
                color8: "#6272a4".to_string(),
                color9: "#ff6e6e".to_string(),
                color10: "#69ff94".to_string(),
                color11: "#ffb86c".to_string(),
                color12: "#d6acff".to_string(),
                color13: "#ff92df".to_string(),
                color14: "#a4ffff".to_string(),
                color15: "#ffffff".to_string(),
            },
        },
        ThemeDefinition {
            name: "rose-pine".to_string(),
            display_name: Some("Rosé Pine".to_string()),
            polarity: "dark".to_string(),
            colors: PaletteColors {
                background: "#191724".to_string(),
                foreground: "#e0def4".to_string(),
                cursor: "#e0def4".to_string(),
                accent: "#ebbcba".to_string(),
                color0: "#26233a".to_string(),
                color1: "#eb6f92".to_string(),
                color2: "#31748f".to_string(),
                color3: "#f6c177".to_string(),
                color4: "#9ccfd8".to_string(),
                color5: "#c4a7e7".to_string(),
                color6: "#ebbcba".to_string(),
                color7: "#e0def4".to_string(),
                color8: "#6e6a86".to_string(),
                color9: "#eb6f92".to_string(),
                color10: "#31748f".to_string(),
                color11: "#ea9a97".to_string(),
                color12: "#9ccfd8".to_string(),
                color13: "#c4a7e7".to_string(),
                color14: "#ebbcba".to_string(),
                color15: "#e0def4".to_string(),
            },
        },
        ThemeDefinition {
            name: "rose-pine-dawn".to_string(),
            display_name: Some("Rosé Pine Dawn".to_string()),
            polarity: "light".to_string(),
            colors: PaletteColors {
                background: "#faf4ed".to_string(),
                foreground: "#575279".to_string(),
                cursor: "#575279".to_string(),
                accent: "#d7827e".to_string(),
                color0: "#fffaf3".to_string(),
                color1: "#b4637a".to_string(),
                color2: "#286983".to_string(),
                color3: "#ea9d34".to_string(),
                color4: "#56949f".to_string(),
                color5: "#907aa9".to_string(),
                color6: "#d7827e".to_string(),
                color7: "#575279".to_string(),
                color8: "#9893a5".to_string(),
                color9: "#b4637a".to_string(),
                color10: "#286983".to_string(),
                color11: "#ea9d34".to_string(),
                color12: "#56949f".to_string(),
                color13: "#907aa9".to_string(),
                color14: "#d7827e".to_string(),
                color15: "#575279".to_string(),
            },
        },
        ThemeDefinition {
            name: "everforest-dark".to_string(),
            display_name: Some("Everforest Dark".to_string()),
            polarity: "dark".to_string(),
            colors: PaletteColors {
                background: "#2d353b".to_string(),
                foreground: "#d3c6aa".to_string(),
                cursor: "#d3c6aa".to_string(),
                accent: "#a7c080".to_string(),
                color0: "#232a2e".to_string(),
                color1: "#e67e80".to_string(),
                color2: "#a7c080".to_string(),
                color3: "#dbbc7f".to_string(),
                color4: "#7fbbb3".to_string(),
                color5: "#d699b6".to_string(),
                color6: "#83c092".to_string(),
                color7: "#d3c6aa".to_string(),
                color8: "#475258".to_string(),
                color9: "#e67e80".to_string(),
                color10: "#a7c080".to_string(),
                color11: "#e69875".to_string(),
                color12: "#7fbbb3".to_string(),
                color13: "#d699b6".to_string(),
                color14: "#83c092".to_string(),
                color15: "#d3c6aa".to_string(),
            },
        },
        ThemeDefinition {
            name: "everforest-light".to_string(),
            display_name: Some("Everforest Light".to_string()),
            polarity: "light".to_string(),
            colors: PaletteColors {
                background: "#fdf6e3".to_string(),
                foreground: "#5c6a72".to_string(),
                cursor: "#5c6a72".to_string(),
                accent: "#8da101".to_string(),
                color0: "#fdf6e3".to_string(),
                color1: "#f85552".to_string(),
                color2: "#8da101".to_string(),
                color3: "#dfa000".to_string(),
                color4: "#3a94c5".to_string(),
                color5: "#df69ba".to_string(),
                color6: "#35a77c".to_string(),
                color7: "#5c6a72".to_string(),
                color8: "#939f91".to_string(),
                color9: "#f85552".to_string(),
                color10: "#8da101".to_string(),
                color11: "#f57d26".to_string(),
                color12: "#3a94c5".to_string(),
                color13: "#df69ba".to_string(),
                color14: "#35a77c".to_string(),
                color15: "#5c6a72".to_string(),
            },
        },
        ThemeDefinition {
            name: "one-dark".to_string(),
            display_name: Some("One Dark".to_string()),
            polarity: "dark".to_string(),
            colors: PaletteColors {
                background: "#282c34".to_string(),
                foreground: "#abb2bf".to_string(),
                cursor: "#528bff".to_string(),
                accent: "#61afef".to_string(),
                color0: "#1e2127".to_string(),
                color1: "#e06c75".to_string(),
                color2: "#98c379".to_string(),
                color3: "#e5c07b".to_string(),
                color4: "#61afef".to_string(),
                color5: "#c678dd".to_string(),
                color6: "#56b6c2".to_string(),
                color7: "#abb2bf".to_string(),
                color8: "#5c6370".to_string(),
                color9: "#e06c75".to_string(),
                color10: "#98c379".to_string(),
                color11: "#d19a66".to_string(),
                color12: "#61afef".to_string(),
                color13: "#c678dd".to_string(),
                color14: "#56b6c2".to_string(),
                color15: "#ffffff".to_string(),
            },
        },
        ThemeDefinition {
            name: "kanagawa".to_string(),
            display_name: Some("Kanagawa Wave".to_string()),
            polarity: "dark".to_string(),
            colors: PaletteColors {
                background: "#1f1f28".to_string(),
                foreground: "#dcd7ba".to_string(),
                cursor: "#c8c093".to_string(),
                accent: "#7e9cd8".to_string(),
                color0: "#16161d".to_string(),
                color1: "#c34043".to_string(),
                color2: "#76946a".to_string(),
                color3: "#c0a36e".to_string(),
                color4: "#7e9cd8".to_string(),
                color5: "#957fb8".to_string(),
                color6: "#6a9589".to_string(),
                color7: "#c8c093".to_string(),
                color8: "#727169".to_string(),
                color9: "#e82424".to_string(),
                color10: "#98bb6c".to_string(),
                color11: "#ffa066".to_string(),
                color12: "#7fb4ca".to_string(),
                color13: "#938aa9".to_string(),
                color14: "#7aa89f".to_string(),
                color15: "#dcd7ba".to_string(),
            },
        },
        ThemeDefinition {
            name: "monokai-pro".to_string(),
            display_name: Some("Monokai Pro".to_string()),
            polarity: "dark".to_string(),
            colors: PaletteColors {
                background: "#2d2a2e".to_string(),
                foreground: "#fcfcfa".to_string(),
                cursor: "#fcfcfa".to_string(),
                accent: "#ffd866".to_string(),
                color0: "#221f22".to_string(),
                color1: "#ff6188".to_string(),
                color2: "#a9dc76".to_string(),
                color3: "#ffd866".to_string(),
                color4: "#78dce8".to_string(),
                color5: "#ab9df2".to_string(),
                color6: "#fc9867".to_string(),
                color7: "#fcfcfa".to_string(),
                color8: "#727072".to_string(),
                color9: "#ff6188".to_string(),
                color10: "#a9dc76".to_string(),
                color11: "#ffd866".to_string(),
                color12: "#78dce8".to_string(),
                color13: "#ab9df2".to_string(),
                color14: "#fc9867".to_string(),
                color15: "#ffffff".to_string(),
            },
        },
        ThemeDefinition {
            name: "ayu-dark".to_string(),
            display_name: Some("Ayu Dark".to_string()),
            polarity: "dark".to_string(),
            colors: PaletteColors {
                background: "#0b0e14".to_string(),
                foreground: "#b3b1ad".to_string(),
                cursor: "#e6b450".to_string(),
                accent: "#ffb454".to_string(),
                color0: "#01060e".to_string(),
                color1: "#ea6c73".to_string(),
                color2: "#7fd962".to_string(),
                color3: "#f9af4f".to_string(),
                color4: "#53bdfa".to_string(),
                color5: "#c397d8".to_string(),
                color6: "#90e1c6".to_string(),
                color7: "#c7c7c7".to_string(),
                color8: "#686868".to_string(),
                color9: "#f07178".to_string(),
                color10: "#aad94c".to_string(),
                color11: "#ffb454".to_string(),
                color12: "#59c2ff".to_string(),
                color13: "#d2a6ff".to_string(),
                color14: "#95e6cb".to_string(),
                color15: "#ffffff".to_string(),
            },
        },
        ThemeDefinition {
            name: "ayu-mirage".to_string(),
            display_name: Some("Ayu Mirage".to_string()),
            polarity: "dark".to_string(),
            colors: PaletteColors {
                background: "#1f2430".to_string(),
                foreground: "#cbccc6".to_string(),
                cursor: "#ffcc66".to_string(),
                accent: "#ffcc66".to_string(),
                color0: "#191e2a".to_string(),
                color1: "#ed8274".to_string(),
                color2: "#a6cc70".to_string(),
                color3: "#fad07b".to_string(),
                color4: "#6dcbfa".to_string(),
                color5: "#cfbafa".to_string(),
                color6: "#90e1c6".to_string(),
                color7: "#c7c7c7".to_string(),
                color8: "#707a8c".to_string(),
                color9: "#f28779".to_string(),
                color10: "#bae67e".to_string(),
                color11: "#ffd580".to_string(),
                color12: "#73d0ff".to_string(),
                color13: "#d4bfff".to_string(),
                color14: "#95e6cb".to_string(),
                color15: "#ffffff".to_string(),
            },
        },
        ThemeDefinition {
            name: "solarized-dark".to_string(),
            display_name: Some("Solarized Dark".to_string()),
            polarity: "dark".to_string(),
            colors: PaletteColors {
                background: "#002b36".to_string(),
                foreground: "#839496".to_string(),
                cursor: "#93a1a1".to_string(),
                accent: "#268bd2".to_string(),
                color0: "#073642".to_string(),
                color1: "#dc322f".to_string(),
                color2: "#859900".to_string(),
                color3: "#b58900".to_string(),
                color4: "#268bd2".to_string(),
                color5: "#d33682".to_string(),
                color6: "#2aa198".to_string(),
                color7: "#eee8d5".to_string(),
                color8: "#586e75".to_string(),
                color9: "#cb4b16".to_string(),
                color10: "#586e75".to_string(),
                color11: "#657b83".to_string(),
                color12: "#839496".to_string(),
                color13: "#6c71c4".to_string(),
                color14: "#93a1a1".to_string(),
                color15: "#fdf6e3".to_string(),
            },
        },
        ThemeDefinition {
            name: "solarized-light".to_string(),
            display_name: Some("Solarized Light".to_string()),
            polarity: "light".to_string(),
            colors: PaletteColors {
                background: "#fdf6e3".to_string(),
                foreground: "#657b83".to_string(),
                cursor: "#586e75".to_string(),
                accent: "#268bd2".to_string(),
                color0: "#eee8d5".to_string(),
                color1: "#dc322f".to_string(),
                color2: "#859900".to_string(),
                color3: "#b58900".to_string(),
                color4: "#268bd2".to_string(),
                color5: "#d33682".to_string(),
                color6: "#2aa198".to_string(),
                color7: "#073642".to_string(),
                color8: "#93a1a1".to_string(),
                color9: "#cb4b16".to_string(),
                color10: "#93a1a1".to_string(),
                color11: "#839496".to_string(),
                color12: "#657b83".to_string(),
                color13: "#6c71c4".to_string(),
                color14: "#586e75".to_string(),
                color15: "#002b36".to_string(),
            },
        },
        ThemeDefinition {
            name: "cyberpunk".to_string(),
            display_name: Some("Cyberpunk Neon".to_string()),
            polarity: "dark".to_string(),
            colors: PaletteColors {
                background: "#10101a".to_string(),
                foreground: "#e0fbff".to_string(),
                cursor: "#00ffc8".to_string(),
                accent: "#ff007f".to_string(),
                color0: "#08080f".to_string(),
                color1: "#ff0055".to_string(),
                color2: "#00ff9f".to_string(),
                color3: "#ffe600".to_string(),
                color4: "#00b8ff".to_string(),
                color5: "#d600ff".to_string(),
                color6: "#00f0ff".to_string(),
                color7: "#e0fbff".to_string(),
                color8: "#4b4f69".to_string(),
                color9: "#ff3377".to_string(),
                color10: "#33ffb2".to_string(),
                color11: "#ffaa00".to_string(),
                color12: "#33c6ff".to_string(),
                color13: "#df33ff".to_string(),
                color14: "#33f3ff".to_string(),
                color15: "#ffffff".to_string(),
            },
        },
    ]
}
