# =============================================================================
#  Auto-generated by sl-render - Fish Shell Abbreviations & Aliases
# =============================================================================

alias .sl="cd ~/.config/shoelace/"

alias sl="cd ~/shoelace"

alias d="cd ~/shoelace"

alias c="cd ~/.config"

alias ls="eza --icons --group-directories-first"

alias ll="eza -l --icons --git --group-directories-first"

alias la="eza -la --icons --git --group-directories-first"

alias lt="eza --tree --icons --level=2"

alias cat="bat --style=header,grid"

alias grep="rg"

alias find="fd"

alias top="btop"

alias q="exit"

alias n="niri"
