[general]
font-sans = "JetBrainsMono Nerd Font"

[bar]
scale = 0.75
padding = 0.44999998807907104
bg = "bg-base"
background-opacity = 69
shadow = "drop"
button-variant = "icon-square"
button-icon-size = 0.75
button-icon-padding = 1.25
button-label-weight = "medium"
button-label-padding = 0.25

[[bar.layout]]
monitor = "*"
show = true
left = [
    "custom-nixos-launcher",
    "niri-workspaces",
    "window-title",
]
center = [
    "media",
    "clock",
    "systray",
]
right = [
    "custom-cpu-temp",
    "cpu",
    "notifications",
    "network",
    "brightness",
    "battery",
    "volume",
    "power",
]

[styling.palette]
bg = "#16161e"
surface = "#1a1b26"
elevated = "#292e42"
fg = "#c0caf5"
fg-muted = "#a9b1d6"
primary = "#7aa2f7"
red = "#f7768e"
yellow = "#e0af68"
green = "#9ece6a"
blue = "#7dcfff"

[modules.power]
left-click = "wlogout"

[modules.volume]
dropdown-app-icons = "native"

[[modules.custom]]
id = "cpu-temp"
command = '''sensors | awk '/^Tctl:/ {sub(/\+/,"",$2); print $2}''''
mode = "poll"
interval-ms = 5000
restart-policy = "never"
restart-interval-ms = 1000
format = "{{ output }}"
hide-if-empty = false
icon-name = "ld-thermometer-symbolic"
icon-show = true
icon-color = "auto"
icon-bg-color = "auto"
label-show = true
label-color = "auto"
label-max-length = 0
button-bg-color = "bg-surface-elevated"
border-show = false
border-color = "auto"
left-click = ""
right-click = ""
middle-click = ""
scroll-up = ""
scroll-down = ""

[[modules.custom]]
id = "nixos-launcher"
command = "true"
mode = "poll"
interval-ms = 5000
restart-policy = "never"
restart-interval-ms = 1000
format = "Nixos"
hide-if-empty = false
icon-name = "nix-snowflake"
icon-show = true
icon-color = "auto"
icon-bg-color = "auto"
label-show = true
label-color = "auto"
label-max-length = 0
button-bg-color = "bg-surface-elevated"
border-show = false
border-color = "auto"
left-click = "fuzzel"
right-click = "zen-beta"
middle-click = ""
scroll-up = ""
scroll-down = ""

[osd]
duration = 500
margin = 50.0

[wallpaper]
engine-enabled = false
cycling-enabled = true
cycling-directory = "/home/rsh/ws/walls"
cycling-same-image = true

[[wallpaper.monitors]]
name = ""
fit-mode = "fill"
wallpaper = ""
