[general]
font-sans = "JetBrainsMono Nerd Font"

[bar]
scale = 0.75
padding = 0.10000000149011612
padding-ends = 0.20000000298023224
module-gap = 0.25
bg = "bg-base"
background-opacity = 90
button-variant = "basic"
button-icon-size = 0.75
button-icon-padding = 0.25
button-label-weight = "medium"
button-label-padding = 0.25
button-rounding = "none"
button-gap = 0.5
button-border-location = "none"
button-border-width = 0

[[bar.layout]]
monitor = "*"
show = true
left = ["custom-nixos-launcher", "niri-workspaces", "window-title"]
center = ["media", "clock", "systray", "cava"]
right = [
  "network",
  "bluetooth",
  "notifications",
  "brightness",
  "volume",
  "cpu",
  "custom-cpu-temp",
  "battery",
  "power",
]

[styling]
scale = 0.949999988079071
rounding = "none"

[styling.palette]
bg = "#16161e"
surface = "#1a1b26"
elevated = "#292e42"
fg = "#c0caf5"
fg-muted = "#a9b1d6"
primary = "#7aa2f7"
red = "#f7768e"
yellow = "#e0af68"
green = "#9ece6a"
blue = "#7dcfff"

[modules.battery]
icon-bg-color = "accent"
label-color = "accent"

[modules.brightness]
icon-bg-color = "accent-hover"
label-color = "accent"
scroll-up = "brightnessctl s 1%+"
scroll-down = "brightnessctl s 1%-"

[modules.cava]
style = "peaks"
bar-width = 4
bar-gap = 2

[modules.clock]
format = "%I:%M"
icon-name = "time-symbolic"
icon-show = false
label-color = "status-warning"

[modules.cpu]
border-color = "accent"
icon-bg-color = "accent"
label-color = "accent"
right-click = "kitty -e btop"

[modules.mango-workspaces]
app-icons-show = true
border-show = true

[modules.media]
border-color = "accent"
icon-bg-color = "accent"
label-color = "accent"
label-max-length = 15
right-click = "focus:this"

[modules.notifications]
icon-bg-color = "blue"
label-color = "blue"
icon-source = "application"
popup-close-behavior = "remove"

[modules.power]
left-click = "wlogout"

[modules.volume]
border-color = "accent"
icon-bg-color = "accent"
label-color = "accent"
right-click = "pwvucontrol"
scroll-up = "pamixer -i 1"
scroll-down = "pamixer -d 1"
dropdown-app-icons = "native"

[modules.window-title]
label-max-length = 30
left-click = "niri msg action close-window"

[[modules.custom]]
id = "cpu-temp"
command = '''sensors | awk '/^Tctl:/ {sub(/\+/,"",$2); print $2}''''
mode = "poll"
interval-ms = 5000
restart-policy = "never"
restart-interval-ms = 1000
format = "{{ output }}"
hide-if-empty = false
icon-name = "ld-thermometer-symbolic"
icon-show = true
icon-color = "auto"
icon-bg-color = "auto"
label-show = true
label-color = "auto"
label-max-length = 0
button-bg-color = "bg-surface-elevated"
border-show = false
border-color = "auto"
left-click = ""
right-click = "kitty -e batmon"
middle-click = ""
scroll-up = ""
scroll-down = ""

[[modules.custom]]
id = "nixos-launcher"
command = "true"
mode = "poll"
interval-ms = 5000
restart-policy = "never"
restart-interval-ms = 1000
format = "Nixos"
hide-if-empty = false
icon-name = "nix-snowflake"
icon-show = true
icon-color = "auto"
icon-bg-color = "auto"
label-show = true
label-color = "auto"
label-max-length = 0
button-bg-color = "bg-surface-elevated"
border-show = false
border-color = "auto"
left-click = "fuzzel"
right-click = "zen-beta"
middle-click = ""
scroll-up = ""
scroll-down = ""

[osd]
duration = 500
margin = 50.0

[wallpaper]
engine-enabled = false
cycling-enabled = true
cycling-directory = "/home/rsh/ws/walls"
cycling-same-image = true

[[wallpaper.monitors]]
name = ""
fit-mode = "fill"
wallpaper = ""
