name = "cyberpunk"
display_name = "Cyberpunk Neon"
polarity = "dark"

[colors]
background = "#10101a"
foreground = "#e0fbff"
cursor = "#00ffc8"
accent = "#ff007f"

color0 = "#08080f"
color1 = "#ff0055"
color2 = "#00ff9f"
color3 = "#ffe600"
color4 = "#00b8ff"
color5 = "#d600ff"
color6 = "#00f0ff"
color7 = "#e0fbff"
color8 = "#4b4f69"
color9 = "#ff3377"
color10 = "#33ffb2"
color11 = "#ffaa00"
color12 = "#33c6ff"
color13 = "#df33ff"
color14 = "#33f3ff"
color15 = "#ffffff"
