name = "monokai-pro"
display_name = "Monokai Pro"
polarity = "dark"

[colors]
background = "#2d2a2e"
foreground = "#fcfcfa"
cursor = "#fcfcfa"
accent = "#ffd866"

color0 = "#221f22"
color1 = "#ff6188"
color2 = "#a9dc76"
color3 = "#ffd866"
color4 = "#78dce8"
color5 = "#ab9df2"
color6 = "#fc9867"
color7 = "#fcfcfa"
color8 = "#727072"
color9 = "#ff6188"
color10 = "#a9dc76"
color11 = "#ffd866"
color12 = "#78dce8"
color13 = "#ab9df2"
color14 = "#fc9867"
color15 = "#ffffff"
