# =============================================================================
#  Default Applications & MIME Handlers (env/token.kv/apps.toml)
# =============================================================================

terminal = "kitty"
editor = "codium"
browser = "google-chrome"
fileManager = "thunar"
pdfViewer = "readest"
videoPlayer = "mpv"
audioPlayer = "vlc"
imageViewer = "imv"
