{
  imports = [
    ./apps/antigravity.nix
    ./apps/helium.nix
    ./apps/librewolf.nix
    ./apps/obs.nix
    ./apps/plain-app.nix
    ./apps/qutebrowser.nix
    ./apps/zen-browser.nix
    ./de/budgie.nix
    ./de/xfce.nix
    ./display-manager/gdm.nix
    ./display-manager/ly.nix
    ./display-manager/tuigreet.nix
    ./hardware/amd.nix
    ./hardware/bluetooth.nix
    ./hardware/intel.nix
    ./hardware/power.nix
    ./hm/environment.nix
    ./hm/fhs.nix
    ./hm/git.nix
    ./hm/mime.nix
    ./hm/packages.nix
    ./hm/symlinks.nix
    ./services/desktop-services.nix
    ./services/kanata.nix
    ./services/polkit.nix
    ./services/xdg-portals.nix
    ./system/boot-and-kernel.nix
    ./system/cache-storage.nix
    ./system/networking.nix
    ./system/nix-settings.nix
    ./system/time-and-locale.nix
    ./system/user-accounts.nix
    ./theme/stylix-hm.nix
    ./theme/stylix-system.nix
    ./virtualization/appimage.nix
    ./virtualization/distrobox.nix
    ./virtualization/libvirt.nix
    ./virtualization/vm-runner.nix
    ./virtualization/waydroid.nix
    ./wm/swaybg.nix
    ./wm/wayle.nix
    ./wm/wl-clipboard.nix
  ];
}
