# =============================================================================
#  Wallust Generated Kitty Color Scheme
# =============================================================================

background #191724
foreground #E0DEF4
selection_background #6E6A86
selection_foreground #E0DEF4
url_color #9CCFD8
cursor #E0DEF4
cursor_text_color #191724

active_tab_background #C4A7E7
active_tab_foreground #191724
inactive_tab_background #191724
inactive_tab_foreground #E0DEF4
tab_bar_background #191724

active_border_color #C4A7E7
inactive_border_color #191724
bell_border_color #EB6F92

color0 #191724
color1 #EB6F92
color2 #31748F
color3 #EBBCBA
color4 #C4A7E7
color5 #F6C177
color6 #9CCFD8
color7 #E0DEF4
color8 #6E6A86
color9 #EB6F92
color10 #31748F
color11 #F6C177
color12 #C4A7E7
color13 #F6C177
color14 #9CCFD8
color15 #524F67
