# =============================================================================
#  Wallust Generated Kitty Color Scheme
# =============================================================================

background #1E1E2E
foreground #CDD6F4
selection_background #6C7086
selection_foreground #CDD6F4
url_color #94E2D5
cursor #CDD6F4
cursor_text_color #1E1E2E

active_tab_background #89B4FA
active_tab_foreground #1E1E2E
inactive_tab_background #1E1E2E
inactive_tab_foreground #CDD6F4
tab_bar_background #1E1E2E

active_border_color #89B4FA
inactive_border_color #1E1E2E
bell_border_color #F38BA8

color0 #1E1E2E
color1 #F38BA8
color2 #A6E3A1
color3 #F9E2AF
color4 #89B4FA
color5 #CBA6F7
color6 #94E2D5
color7 #CDD6F4
color8 #6C7086
color9 #F38BA8
color10 #A6E3A1
color11 #FAB387
color12 #89B4FA
color13 #CBA6F7
color14 #94E2D5
color15 #B4BEFE
