# =============================================================================
#  Wallust Generated Fuzzel Palette
# =============================================================================

[colors]
background=191724f2
text=E0DEF4ff
prompt=C4A7E7ff
placeholder=6E6A86ff
input=E0DEF4ff
match=F6C177ff
selection=6E6A86ff
selection-text=E0DEF4ff
selection-match=9CCFD8ff
border=C4A7E7ff
