# =============================================================================
#  Wallust Generated Fuzzel Palette
# =============================================================================

[colors]
background=1E1E2Ef2
text=CDD6F4ff
prompt=89B4FAff
placeholder=6C7086ff
input=CDD6F4ff
match=CBA6F7ff
selection=6C7086ff
selection-text=CDD6F4ff
selection-match=94E2D5ff
border=89B4FAff
