# =============================================================================
#  Fuzzel Application Launcher (Tokyo Night Sharp Aesthetic)
#  Location: ~/.config/fuzzel/fuzzel.ini
# =============================================================================

[main]
# Include external modular variables & colors
include=~/.config/fuzzel/sl_appearance.ini
include=~/.config/fuzzel/sl_colors.ini

# Prompts & Dimensions
dpi-aware=auto
prompt="❯ "
placeholder="Search apps, utilities, tools..."

# Window Dimensions & Layout
width=30
lines=15
horizontal-pad=30
vertical-pad=26
inner-pad=20
tabs=4

# Icons & Default Terminal
icons-enabled=yes
icon-theme=Tela-circle

[dmenu]
mode=text
exit-immediately-if-empty=no
