# =============================================================================
#  Wallust Generated wayle theme ( colors.toml )
# =============================================================================

[styling.palette]
bg = "{{background}}"
surface = "{{background}}"
elevated = "{{color0}}"
fg = "{{foreground}}"
fg-muted = "{{color7}}"
primary = "{{color13}}"
red = "{{color1}}"
yellow = "{{color3}}"
green = "{{color2}}"
blue = "{{color12}}"

