# =============================================================================
#  Kitty Font Configuration
# =============================================================================

font_family      JetBrainsMono NF
italic_font      VictorMono NF Medium Italic 
font_features    VictorMono-Medium +ss01
font_size        18.0
