# =============================================================================
#  Kitty Terminal Emulator Configuration
# =============================================================================

# 1. External Imports
include ./tokyo_night.conf
include ~/.config/kitty/fonts.conf
include ~/.config/kitty/keymaps.conf

# 2. General & Shell
shell fish
confirm_os_window_close 0
allow_remote_control yes

# 3. Cursor & Animation Effects
cursor_shape beam
cursor_trail 4
cursor_trail_decay 0.1 0.6
cursor_trail_start_threshold 1

# 4. Window Geometry & Decoration
remember_window_position yes
hide_window_decorations no
placement_strategy center
window_border_width 0
draw_minimal_borders no
window_margin_width 0
window_padding_width 0

# 5. Background & Transparency
background_opacity 0.8

# 6. Tab Bar Layout
tab_bar_edge bottom
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0
