# =============================================================================
#  Yazi Theme Index - Active Flavor Configuration
# =============================================================================

[flavor]
dark = "wallust"
light = "wallust"
