# =============================================================================
#  Auto-generated by sl-render - Bash Session Environment (env.bash)
# =============================================================================

export EDITOR="nvim"
export VISUAL="nvim"
export TERMINAL="kitty"
export BROWSER="google-chrome"
export SHOELACE_DIR="~/shoelace"
export sl-agy-alias="~/agy-conv/sl-agy"
export THEME="rose-pine"

# Binary Search Paths
export PATH="~/.local/bin:$PATH"
export PATH="~/.cargo/bin:$PATH"
export PATH="~/.nix-profile/bin:$PATH"
export PATH="/etc/profiles/per-user/rsh/bin:$PATH"
export PATH="~/agy-conv/:$PATH"
