# =============================================================================
#  Default Applications & MIME Handlers (env/tokens/apps.toml)
# =============================================================================

terminal = "kitty"
editor = "codium"
browser = "helium"
fileManager = "nemo"
pdfViewer = "readest"
videoPlayer = "mpv"
audioPlayer = "vlc"
imageViewer = "imv"
