# =============================================================================
#  Nushell Environment Loader (env.nu)
# =============================================================================

# Load dynamic environment variables generated by Shoelace
source ~/.config/nushell/sl_env.nu

# Load dynamic path additions generated by Shoelace
source ~/.config/nushell/sl_path.nu
