# =============================================================================
#  Auto-generated by sl-render - Nushell Session Environment (env.nu)
# =============================================================================

$env.EDITOR = "nvim"
$env.VISUAL = "nvim"
$env.TERMINAL = "kitty"
$env.BROWSER = "google-chrome"
$env.SHOELACE_DIR = "~/shoelace"
$env.sl-agy-alias = "~/agy-conv/sl-agy"
$env.THEME = "rose-pine"
