# =============================================================================
#  Auto-generated by sl-render - Nushell Binary Paths (path.nu)
# =============================================================================

use std/util "path add"

path add ("~/.local/bin" | path expand)
path add ("~/.cargo/bin" | path expand)
path add ("~/.nix-profile/bin" | path expand)
path add ("/etc/profiles/per-user/rsh/bin" | path expand)
path add ("~/agy-conv/" | path expand)
