[fonts.mono]
family = "JetBrainsMono Nerd Font"
italic_family = "JetBrainsMono Nerd Font"
features = ""

[fonts.sans]
family = "Inter"
style = "Regular"

[fonts.serif]
family = "Inter"
style = "Regular"

[fonts.emoji]
family = "Noto Color Emoji"

[fonts.sizes]
terminal = 18.0
bar = 12.0
launcher = 18.0
desktop = 16.0
power_menu = 14.0
fastfetch_logo = 16.0

[appearance]
border_radius = 18
border_width = 1
icon_theme = "Tela-circle-dark"

[appearance.gaps]
inner = 6
outer = 6
bar_gap = 2

[appearance.opacity]
terminal = 0.9
bar = 0.9
overlay = 0.88

[appearance.cursor]
name = "Bibata-Modern-Ice"
size = 42

[theme]
active = "rose-pine"
polarity = "dark"
