# =============================================================================
#  Auto-generated by sl-render - Fish Shell Abbreviations & Aliases
# =============================================================================

{{#each alias}}
alias {{key}}="{{{value}}}"
{{/each alias}}
