# =============================================================================
#  Auto-generated by sl-render - Fish Shell Abbreviations & Aliases
# =============================================================================

{% for key, val in alias|items %}
abbr --add {{ key }} {{ val }}
{% endfor %}
