# =============================================================================
#  Auto-generated by sl-render - Fish Shell Environment Variables
# =============================================================================

{% if editor is defined and editor %}
set -gx EDITOR {{ editor }}
set -gx VISUAL {{ editor }}
{% endif %}
{% if terminal is defined and terminal %}
set -gx TERMINAL {{ terminal }}
{% endif %}
{% if browser is defined and browser %}
set -gx BROWSER {{ browser }}
{% endif %}

{% if env is defined %}
{% for key, val in env|items %}
set -gx {{ key }} {{ val }}
{% endfor %}
{% endif %}
