# =============================================================================
#  Auto-generated by sl-render - Fish Shell Environment Variables
# =============================================================================

{% for key, val in env|items %}
set -gx {{ key }} {{ val }}
{% endfor %}
