# =============================================================================
#  Auto-generated by sl-render - Fish Shell Environment Paths
# =============================================================================

{% for path in paths %}
fish_add_path -g "{{ path }}"
{% endfor %}
