# =============================================================================
#  Auto-generated by sl-render - Bash Session Environment (env.bash)
# =============================================================================

{{#env_vars}}
export {{name}}="{{{value}}}"
{{/env_vars}}
export THEME="{{theme}}"

# Binary Search Paths
{{#paths}}
export PATH="{{.}}:$PATH"
{{/paths}}
