# =============================================================================
#  Auto-generated by sl-render - Fish Shell Abbreviations & Aliases (aliases.fish)
# =============================================================================

{{#aliases}}
alias {{name}}="{{{command}}}"
{{/aliases}}
