# =============================================================================
#  Auto-generated by sl-render - Fish Binary Paths & Session (paths.fish)
# =============================================================================

# Paths
{{#paths}}
fish_add_path -g {{.}}
{{/paths}}

# Environment Variables
{{#env_vars}}
set -gx {{name}} "{{{value}}}"
{{/env_vars}}
set -gx THEME "{{theme}}"
