# =============================================================================
#  Auto-generated by sl-render - Nushell Binary Paths (path.nu)
# =============================================================================

use std/util "path add"

{{#paths}}
path add ("{{.}}" | path expand)
{{/paths}}
