# =============================================================================
#  Auto-generated by sl-render - Nushell Session Environment (env.nu)
# =============================================================================

{{#env_vars}}
$env.{{name}} = "{{{value}}}"
{{/env_vars}}
$env.THEME = "{{theme}}"
