# =============================================================================
#  Auto-generated by sl-render - Zsh Session Environment (env.zsh)
# =============================================================================

{{#env_vars}}
export {{name}}="{{{value}}}"
{{/env_vars}}
export THEME="{{theme}}"

# Binary Search Paths
typeset -U path
path=(
  {{#paths}}
  {{.}}
  {{/paths}}
  $path
)
export PATH
