# =============================================================================
#  Auto-generated by sl-render - Fish Shell Abbreviations & Aliases
# =============================================================================

{ { #aliases}}
        alias {{name}}="{{{command}}}"
        { { /aliases } }
