name = "tokyo-night-day"
display_name = "Tokyo Night Day"
polarity = "light"

[colors]
background = "#e1e2e7"
foreground = "#3760bf"
cursor = "#3760bf"
accent = "#2e7de9"

color0 = "#e1e2e7"
color1 = "#f52a65"
color2 = "#587539"
color3 = "#8c6c3e"
color4 = "#2e7de9"
color5 = "#9854f1"
color6 = "#007197"
color7 = "#6172b0"
color8 = "#a8aecb"
color9 = "#f52a65"
color10 = "#587539"
color11 = "#b15c00"
color12 = "#2e7de9"
color13 = "#9854f1"
color14 = "#007197"
color15 = "#3760bf"
