# =============================================================================
#  Desktop Theme & Color Palette (Stylix & Base16)
# =============================================================================

theme = "rose-pine"
polarity = "dark"   # "dark" | "light"
