# =============================================================================
#  Auto-generated by sl-render - Fish Shell Abbreviations & Aliases
# =============================================================================


alias .sl="cd ~/.config/shoelace/"

alias sl="cd ~/shoelace"

alias d="cd ~/shoelace"

alias c="cd ~/.config"

alias ls="eza --icons --group-directories-first"

alias ll="eza -l --icons --git --group-directories-first"

alias la="eza -la --icons --git --group-directories-first"

alias lt="eza --tree --icons --level=2"

alias cat="bat --style=header,grid"

alias top="btop"

alias q="exit"

alias n="niri"

alias pkg-in="nvim ~/shoelace/packages.nix"

alias sl-path="nvim ~/shoelace/tokens/shell.d/path.toml"

alias sl-alias="nvim ~/shoelace/tokens/shell.d/alias.toml ~/shoelace/tokens/shell.d/env.toml"

alias sl-appearance="nvim ~/shoelace/tokens/layout-and-window.toml ~/shoelace/tokens/ui.toml"

