# =============================================================================
#  Auto-generated by sl-render - Fish Shell Abbreviations & Aliases
# =============================================================================


abbr --add open handlr open

abbr --add sl cd ~/.config/shoelace/

abbr --add d cd ~/shoelace

abbr --add c cd ~/.config

abbr --add ls eza --icons --group-directories-first

abbr --add ll eza -l --icons --git --group-directories-first

abbr --add la eza -la --icons --git --group-directories-first

abbr --add lt eza --tree --icons --level=2

abbr --add cat bat --style=header,grid

abbr --add top btop

abbr --add q exit

abbr --add n niri

abbr --add pkg-in nvim ~/shoelace/tokens/pkgs/hm-pkgs.toml

abbr --add add-path nvim ~/shoelace/tokens/shell.d/path.toml

abbr --add add-alias nvim ~/shoelace/tokens/shell.d/alias.toml ~/shoelace/tokens/shell.d/env.toml

abbr --add add-env nvim  ~/shoelace/tokens/shell.d/env.toml

abbr --add add-var nvim  ~/shoelace/tokens/shell.d/env.toml

abbr --add add-variables nvim  ~/shoelace/tokens/shell.d/env.toml

abbr --add edit-appearance nvim ~/shoelace/tokens/layout-and-window.toml ~/shoelace/tokens/ui.toml

