# =============================================================================
#  Auto-generated by sl-render - Fish Shell Environment Variables
# =============================================================================


set -gx EDITOR nvim

set -gx VISUAL nvim

set -gx TERMINAL kitty

set -gx BROWSER google-chrome

set -gx SHOELACE_DIR ~/shoelace

set -gx SL_AGY_ALIAS ~/agy-conv/sl-agy

set -gx CARGO_TARGET_DIR /dev/shm/cargo

