# =============================================================================
#  Auto-generated by sl-render - Fish Shell Environment Variables
# =============================================================================


set -gx EDITOR codium
set -gx VISUAL codium


set -gx TERMINAL kitty


set -gx BROWSER helium




set -gx SHOELACE_DIR ~/shoelace

set -gx SL_AGY_ALIAS ~/agy-conv/sl-agy

set -gx CARGO_TARGET_DIR /dev/shm/cargo


