[general]
font-sans = "JetBrainsMono Nerd Font"

[bar]
scale = 0.8500000238418579
padding = 0.10000000149011612
padding-ends = 0.20000000298023224
module-gap = 0.25
background-opacity = 90
button-variant = "basic"
button-icon-size = 0.75
button-icon-padding = 0.25
button-label-weight = "medium"
button-label-padding = 0.25
button-rounding = "none"
button-gap = 0.5
button-border-location = "none"
button-border-width = 0

[[bar.layout]]
monitor = "*"
show = true
left = ["custom-nixos-launcher", "niri-workspaces", "window-title"]
center = ["media", "clock"]
right = [
  "systray",
  "ram",
  "cpu",
  "network",
  "bluetooth",
  "notifications",
  "volume",
  "brightness",
  "custom-cpu-temp",
  "battery",
  "power",
]

[styling]
scale = 0.949999988079071
rounding = "none"

[styling.palette]
bg = "#191724"
surface = "#191724"
elevated = "#26233a"
fg = "#e0def4"
fg-muted = "#6e6a86"
primary = "#ebbcba"
red = "#eb6f92"
yellow = "#f6c177"
green = "#31748f"
blue = "#9ccfd8"

[modules.battery]
icon-color = "status-warning"
icon-bg-color = "bg-surface-elevated"
label-color = "fg-default"

[modules.bluetooth]
border-show = false
icon-color = "accent"
icon-bg-color = "bg-surface-elevated"
label-color = "fg-default"
button-bg-color = "bg-surface-elevated"

[modules.brightness]
icon-color = "yellow"
icon-bg-color = "bg-surface-elevated"
label-color = "fg-default"
scroll-up = "brightnessctl s 1%+"
scroll-down = "brightnessctl s 1%-"

[modules.cava]
style = "peaks"
bar-width = 4
bar-gap = 2

[modules.clock]
format = "%I:%M"
icon-name = "time-symbolic"
icon-show = false
label-color = "fg-default"

[modules.cpu]
icon-color = "accent"
icon-bg-color = "bg-surface-elevated"
label-color = "fg-default"
right-click = "kitty -e btop"

[modules.dashboard]
icon-bg-color = "bg-surface"

[modules.media]
icon-color = "blue"
icon-bg-color = "bg-surface-elevated"
label-color = "fg-default"
label-max-length = 15
right-click = "focus:this"

[modules.network]
border-show = false
icon-color = "accent"
icon-bg-color = "bg-surface-elevated"
label-color = "fg-default"
button-bg-color = "bg-surface-elevated"

[modules.niri-workspaces]
urgent-show = true
active-indicator = "underline"
active-color = "accent"
occupied-color = "fg-default"
empty-color = "fg-muted"
container-bg-color = "bg-surface-elevated"

[modules.notifications]
icon-color = "accent"
icon-bg-color = "bg-surface-elevated"
label-color = "fg-default"
icon-source = "application"
popup-close-behavior = "remove"

[modules.power]
icon-color = "red"
icon-bg-color = "bg-surface-elevated"
left-click = "power-menu"

[modules.ram]
border-color = "fg-default"
icon-color = "accent"
icon-bg-color = "accent"
label-color = "fg-default"

[modules.volume]
icon-color = "status-warning"
icon-bg-color = "bg-surface-elevated"
label-color = "fg-default"
right-click = "pwvucontrol"
scroll-up = "pamixer -i 1"
scroll-down = "pamixer -d 1"
dropdown-app-icons = "native"

[modules.window-title]
border-show = false
icon-color = "accent"
icon-bg-color = "bg-surface-elevated"
label-color = "fg-default"
label-max-length = 30
button-bg-color = "bg-surface-elevated"
left-click = "niri msg action close-window"

[[modules.custom]]
id = "cpu-temp"
command = '''sensors 2>/dev/null | awk -F: '/^(Tctl|Package id 0|Core 0|temp1):/ { sub(/\+/,"",$2); gsub(/ /,"",$2); print $2; exit }' '''
mode = "poll"
interval-ms = 2000
restart-policy = "never"
restart-interval-ms = 1000
hide-if-empty = false
icon-name = "ld-thermometer-symbolic"
icon-show = true
icon-color = "yellow"
icon-bg-color = "bg-surface-elevated"
label-show = true
label-color = "fg-default"
label-max-length = 0
button-bg-color = "bg-surface-elevated"
border-show = false
border-color = "border-default"
left-click = "kitty -e btop"
right-click = "kitty -e batmon"
middle-click = ""
scroll-up = ""
scroll-down = ""

[[modules.custom]]
id = "nixos-launcher"
command = "true"
mode = "poll"
interval-ms = 5000
restart-policy = "never"
restart-interval-ms = 1000
format = "NixOS"
hide-if-empty = false
icon-name = "si-nixos-symbolic"
icon-show = true
icon-color = "accent"
icon-bg-color = "bg-surface-elevated"
label-show = true
label-color = "fg-default"
label-max-length = 0
button-bg-color = "bg-surface-elevated"
border-show = false
border-color = "border-default"
left-click = "fuzzel"
right-click = "zen-beta"
middle-click = ""
scroll-up = ""
scroll-down = ""

[osd]
duration = 500
margin = 50.0

[wallpaper]
engine-enabled = false
cycling-enabled = true
cycling-directory = "~/Pictures/Wallpapers"
cycling-same-image = true

[[wallpaper.monitors]]
name = ""
fit-mode = "fill"
wallpaper = ""
